create table authors (book_id integer not null, author_id integer not null, primary key (book_id, author_id))
create table book_authors (id integer generated by default as identity, country_of_origin varchar(255), name varchar(255) not null, primary key (id))
create table books (id integer generated by default as identity, finished boolean, title varchar(255) not null, primary key (id))
create table genres (book_id integer not null, genres varchar(255))
create table user_role (user_id integer not null, role varchar(255))
create table users (id integer generated by default as identity, email varchar(128) not null, first_name varchar(128), last_name varchar(128), password varchar(256), primary key (id))
alter table user_role add constraint user_roles_unique unique (user_id, role)
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table authors add constraint FKbehl3hd33f6mf2t4segjnj8jd foreign key (author_id) references book_authors
alter table authors add constraint FKa0aigfuc5sofk40pgpegigvnh foreign key (book_id) references books
alter table genres add constraint FKhuhvegbvuo18ert7qjemntk5a foreign key (book_id) references books
alter table user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
create table authors (book_id integer not null, author_id integer not null, primary key (book_id, author_id))
create table book_authors (id integer generated by default as identity, country_of_origin varchar(255), name varchar(255) not null, primary key (id))
create table books (id integer generated by default as identity, finished boolean, title varchar(255) not null, primary key (id))
create table genres (book_id integer not null, genres varchar(255))
create table user_role (user_id integer not null, role varchar(255))
create table users (id integer generated by default as identity, email varchar(128) not null, first_name varchar(128), last_name varchar(128), password varchar(256), primary key (id))
alter table user_role add constraint user_roles_unique unique (user_id, role)
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table authors add constraint FKbehl3hd33f6mf2t4segjnj8jd foreign key (author_id) references book_authors
alter table authors add constraint FKa0aigfuc5sofk40pgpegigvnh foreign key (book_id) references books
alter table genres add constraint FKhuhvegbvuo18ert7qjemntk5a foreign key (book_id) references books
alter table user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
create table authors (book_id integer not null, author_id integer not null, primary key (book_id, author_id))
create table book_authors (id integer generated by default as identity, country_of_origin varchar(255), name varchar(255) not null, primary key (id))
create table books (id integer generated by default as identity, finished boolean, title varchar(255) not null, primary key (id))
create table genres (book_id integer not null, genres varchar(255))
create table user_role (user_id integer not null, role varchar(255))
create table users (id integer generated by default as identity, email varchar(128) not null, first_name varchar(128), last_name varchar(128), password varchar(256), primary key (id))
alter table user_role add constraint user_roles_unique unique (user_id, role)
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table authors add constraint FKbehl3hd33f6mf2t4segjnj8jd foreign key (author_id) references book_authors
alter table authors add constraint FKa0aigfuc5sofk40pgpegigvnh foreign key (book_id) references books
alter table genres add constraint FKhuhvegbvuo18ert7qjemntk5a foreign key (book_id) references books
alter table user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
create table authors (book_id integer not null, author_id integer not null, primary key (book_id, author_id))
create table book_authors (id integer generated by default as identity, country_of_origin varchar(255), name varchar(255) not null, primary key (id))
create table books (id integer generated by default as identity, finished boolean, title varchar(255) not null, primary key (id))
create table genres (book_id integer not null, genres varchar(255))
create table user_role (user_id integer not null, role varchar(255))
create table users (id integer generated by default as identity, email varchar(128) not null, first_name varchar(128), last_name varchar(128), password varchar(256), primary key (id))
alter table user_role add constraint user_roles_unique unique (user_id, role)
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table authors add constraint FKbehl3hd33f6mf2t4segjnj8jd foreign key (author_id) references book_authors
alter table authors add constraint FKa0aigfuc5sofk40pgpegigvnh foreign key (book_id) references books
alter table genres add constraint FKhuhvegbvuo18ert7qjemntk5a foreign key (book_id) references books
alter table user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
